### ISSUE TITLE
Training on Custom video

### ISSUE THREAD

**Issue by Jalilnkh** [emla2805/vision-transformer#2]
Thank you for sharing your code.

Do you have any idea how we can train the model on our dateset?

I look forward to hearing from you.

**Comment by Cyril9227** [comment]
Should be fairly easy

- Extract the frames from your videos 
- Label them
- Train the model

**Comment by emla2805** [comment]
You can replace the use of Tensorflow-datasets here: https://github.com/emla2805/vision-transformer/blob/9e6e7823e688edd9e2ef8a62c0ec88f775403033/train.py#L28 and instead load your own data. See the Tensorflow guide https://www.tensorflow.org/tutorials/load_data/images on loading images.
